name: Publish Github Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish-gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
